default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: mysql2
  encoding: utf8
  database: accounts-back_development
  username: root
  password: password
  host: 127.0.0.1
  pool: 5
  timeout: 5000


test:
  adapter: mysql2
  encoding: utf8
  database: accounts-back_test
  username: root
  password: password
  host: 127.0.0.1



production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: accounts-back_production
  username: accounts-back
  password: <%= ENV['ACCOUNTS-BACK_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
