# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e8cd1974e7b7853d938166c246a6b16cca416672c977f4e3764ce9082f38e0415a0f840090f2c4a1a29682c9d760bcb41160e0becc7c664fde25a32060f61ee

test:
  secret_key_base: 6f51b46f20f6c1943f38e84897bd03d9b9d34bfe095d7ad8764933b62830c8fe912b727a891181e42241a9917aeedf1862c53b0a3f9cc577f87c874771df103b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
